services:
  - type: web
    name: safeplate
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn safeplate_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: safeplate_project.settings
      - key: DATABASE_URL
        fromDatabase:
          name: safeplate-db
          property: connectionString
      - key: AIRIA_API_KEY
        sync: false
      - key: AIRIA_RECIPE_AGENT_ENDPOINT
        sync: false

databases:
  - name: safeplate-db
    databaseName: safeplate
    user: safeplate
